/**
 * Mock AI Provider
 * For testing and development without consuming live Gemini API credits.
 * Clearly marked as mock data (Rule 62).
 */

import { AIProviderInterface, AIGenerateOptions } from './AIProviderInterface.js';

export class MockAIProvider implements AIProviderInterface {
  public readonly providerName = 'Mock AI Provider (Testing Mode)';

  public async generate(prompt: string, _options?: AIGenerateOptions): Promise<string> {
    if (prompt.includes('Search Intent') || prompt.includes('search intent')) {
      return JSON.stringify({
        primaryIntent: 'how-to',
        secondaryIntent: 'informational',
        userGoal: 'Learn step-by-step how to make quick and delicious chicken dinners with minimal prep.',
        expectedContentType: 'Recipe Guide & Tips',
        expectedDepth: 'Comprehensive',
        likelyQuestions: [
          'What is the easiest way to cook chicken breast without drying it out?',
          'What sides pair best with quick chicken dishes?',
          'Can I prep these recipes ahead of time?'
        ],
        commercialViability: 'medium'
      });
    }

    return `[MOCK AI GENERATED CONTENT for testing]
This is verified test output generated by MockAIProvider to preserve API quotas while validating end-to-end platform workflows.
Topic context: ${prompt.slice(0, 100)}...`;
  }

  public async generateJson<T = unknown>(_prompt: string, _schemaDesc?: string, _options?: AIGenerateOptions): Promise<T> {
    return {
      mock: true,
      message: 'Verified mock structured data response for testing.',
      timestamp: new Date().toISOString()
    } as unknown as T;
  }

  public async stream(prompt: string, onChunk: (chunk: string) => void, _options?: AIGenerateOptions): Promise<string> {
    const text = `[MOCK STREAMING] Streaming verified response for: ${prompt.slice(0, 60)}`;
    for (const char of text.split(' ')) {
      onChunk(char + ' ');
      await new Promise(r => setTimeout(r, 20));
    }
    return text;
  }

  public async analyze(content: string, instructions: string, _options?: AIGenerateOptions): Promise<string> {
    return `[MOCK ANALYSIS] Completed analysis based on instruction: "${instructions}". Content length: ${content.length} characters.`;
  }

  public async rewrite(content: string, instruction: string, _options?: AIGenerateOptions): Promise<string> {
    return `### Improved Section (Mock Pass)
${content}

*Applied improvement based on: ${instruction}*`;
  }

  public async testConnection(): Promise<{ success: boolean; message: string; model: string }> {
    return {
      success: true,
      message: 'Mock AI Provider is operational and ready for testing.',
      model: 'mock-gemini-test',
    };
  }
}
